# Generated by Django 3.1.2 on 2020-11-03 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='category name')),
                ('descripsion', models.CharField(max_length=200, verbose_name='descripsion')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='LeitnerBoxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('M', 'Mean'), ('S', 'Spell')], max_length=1, verbose_name='mode')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('descripsion', models.CharField(max_length=200, verbose_name='descripsion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User of Box')),
            ],
        ),
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='word')),
                ('means', models.TextField(verbose_name='means')),
                ('voice', models.FileField(blank=True, null=True, upload_to='', verbose_name='word voice')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.categorymodel', verbose_name='categorys')),
            ],
        ),
        migrations.CreateModel(
            name='LeitnerItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='last date question')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.leitnerboxmodel', verbose_name='box name')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.wordmodel', verbose_name='word')),
            ],
        ),
    ]
