# Generated by Django 3.1.4 on 2020-12-23 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(verbose_name='front')),
                ('back', models.TextField(verbose_name='back')),
                ('voice', models.FileField(blank=True, null=True, upload_to='', verbose_name='voice')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='LeitnerBoxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('M', 'Mean'), ('D', 'dictation')], max_length=1, verbose_name='mode')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('descripsion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripsion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User of Box')),
            ],
        ),
        migrations.CreateModel(
            name='LeitnerItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='last date question')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.leitnerboxmodel', verbose_name='box name')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.cartmodel', verbose_name='cart')),
            ],
        ),
    ]
