# Generated by Django 3.1.2 on 2020-10-23 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='work key')),
                ('means', models.CharField(max_length=1000, verbose_name='means')),
                ('voice', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LeitnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_mean_date', models.DateField(auto_now_add=True, verbose_name='last date question for mean')),
                ('word_mean_level', models.IntegerField(default=0, verbose_name='mean level')),
                ('word_spell_date', models.DateField(auto_now_add=True, verbose_name='last date question for spell')),
                ('word_spell_level', models.IntegerField(default=0, verbose_name='spell level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user of this word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.wordmodel', verbose_name='word')),
            ],
        ),
    ]
