# Generated by Django 3.1.2 on 2020-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20201023_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='word',
            field=models.CharField(max_length=20, unique=True, verbose_name='work key'),
        ),
    ]
