# Generated by Django 3.1.2 on 2020-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20201023_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitnermodel',
            name='word_mean_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last date question for mean'),
        ),
        migrations.AlterField(
            model_name='leitnermodel',
            name='word_spell_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last date question for spell'),
        ),
    ]
